[2021-09-27 20:52:38 +0000] [13073] [INFO] Starting gunicorn 20.1.0
[2021-09-27 20:52:38 +0000] [13073] [INFO] Listening at: http://0.0.0.0:5000 (13073)
[2021-09-27 20:52:38 +0000] [13073] [INFO] Using worker: sync
[2021-09-27 20:52:38 +0000] [13075] [INFO] Booting worker with pid: 13075
[2021-09-27 20:53:08 +0000] [13073] [INFO] Handling signal: int
[2021-09-27 20:53:08 +0000] [13075] [INFO] Worker exiting (pid: 13075)
[2021-09-27 20:53:08 +0000] [13073] [INFO] Shutting down: Master
[2022-02-03 00:55:11 +0000] [2316] [INFO] Starting gunicorn 20.1.0
[2022-02-03 00:55:11 +0000] [2316] [INFO] Listening at: http://0.0.0.0:5000 (2316)
[2022-02-03 00:55:11 +0000] [2316] [INFO] Using worker: sync
[2022-02-03 00:55:11 +0000] [2319] [INFO] Booting worker with pid: 2319
[2022-02-03 00:55:13 +0000] [2319] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/extras/app/__init__.py", line 7, in <module>
    from app import imagetransform
  File "/home/ubuntu/extras/app/imagetransform.py", line 7, in <module>
    from wand.image import Image
ModuleNotFoundError: No module named 'wand'
[2022-02-03 00:55:13 +0000] [2319] [INFO] Worker exiting (pid: 2319)
[2022-02-03 00:55:13 +0000] [2316] [INFO] Shutting down: Master
[2022-02-03 00:55:13 +0000] [2316] [INFO] Reason: Worker failed to boot.
[2022-02-03 00:55:49 +0000] [2330] [INFO] Starting gunicorn 20.1.0
[2022-02-03 00:55:49 +0000] [2330] [INFO] Listening at: http://0.0.0.0:5000 (2330)
[2022-02-03 00:55:49 +0000] [2330] [INFO] Using worker: sync
[2022-02-03 00:55:49 +0000] [2332] [INFO] Booting worker with pid: 2332
[2022-02-03 00:55:50 +0000] [2332] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/extras/app/__init__.py", line 7, in <module>
    from app import imagetransform
  File "/home/ubuntu/extras/app/imagetransform.py", line 7, in <module>
    from wand.image import Image
ModuleNotFoundError: No module named 'wand'
[2022-02-03 00:55:50 +0000] [2332] [INFO] Worker exiting (pid: 2332)
[2022-02-03 00:55:50 +0000] [2330] [INFO] Shutting down: Master
[2022-02-03 00:55:50 +0000] [2330] [INFO] Reason: Worker failed to boot.
[2022-02-03 00:58:13 +0000] [2347] [INFO] Starting gunicorn 20.1.0
[2022-02-03 00:58:13 +0000] [2347] [INFO] Listening at: http://0.0.0.0:5000 (2347)
[2022-02-03 00:58:13 +0000] [2347] [INFO] Using worker: sync
[2022-02-03 00:58:13 +0000] [2349] [INFO] Booting worker with pid: 2349
[2022-02-03 01:00:32 +0000] [2347] [CRITICAL] WORKER TIMEOUT (pid:2349)
[2022-02-03 01:00:32 +0000] [2349] [INFO] Worker exiting (pid: 2349)
[2022-02-03 01:00:32 +0000] [2417] [INFO] Booting worker with pid: 2417
[2022-02-03 01:22:08 +0000] [2347] [CRITICAL] WORKER TIMEOUT (pid:2417)
[2022-02-03 01:22:08 +0000] [2417] [INFO] Worker exiting (pid: 2417)
[2022-02-03 01:22:08 +0000] [2617] [INFO] Booting worker with pid: 2617
[2022-02-03 01:22:39 +0000] [2347] [CRITICAL] WORKER TIMEOUT (pid:2617)
[2022-02-03 01:22:39 +0000] [2617] [INFO] Worker exiting (pid: 2617)
[2022-02-03 01:22:39 +0000] [2680] [INFO] Booting worker with pid: 2680
[2022-02-03 03:09:39 +0000] [2347] [WARNING] Worker with pid 2680 was terminated due to signal 1
[2022-02-03 03:09:39 +0000] [2905] [INFO] Booting worker with pid: 2905
[2022-02-03 03:09:39 +0000] [2347] [INFO] Handling signal: hup
[2022-02-03 03:09:39 +0000] [2347] [INFO] Hang up: Master
[2022-02-03 03:09:39 +0000] [2906] [INFO] Booting worker with pid: 2906
[2022-02-03 03:09:39 +0000] [2905] [INFO] Worker exiting (pid: 2905)
[2022-02-03 19:05:31 +0000] [2347] [CRITICAL] WORKER TIMEOUT (pid:2906)
[2022-02-03 19:05:31 +0000] [2906] [INFO] Worker exiting (pid: 2906)
[2022-02-03 19:05:31 +0000] [4882] [INFO] Booting worker with pid: 4882
[2022-02-04 06:28:32 +0000] [2347] [CRITICAL] WORKER TIMEOUT (pid:4882)
[2022-02-04 06:28:32 +0000] [4882] [INFO] Worker exiting (pid: 4882)
[2022-02-04 06:28:32 +0000] [6104] [INFO] Booting worker with pid: 6104
[2022-02-04 22:38:42 +0000] [2347] [WARNING] Worker with pid 6104 was terminated due to signal 1
[2022-02-04 22:38:42 +0000] [55692] [INFO] Booting worker with pid: 55692
[2022-02-04 22:38:42 +0000] [2347] [INFO] Handling signal: term
[2022-02-04 22:38:43 +0000] [55692] [INFO] Worker exiting (pid: 55692)
[2022-02-04 22:38:44 +0000] [2347] [INFO] Shutting down: Master
